packages:
  - "packages/*"
  - "apps/*"

catalog:
  "@ai-sdk/react": "^3.0.129"
  "@better-auth/expo": 1.5.5
  "@cloudflare/workers-types": "^4.20260313.1"
  "@libsql/client": "^0.15.12"
  "@orpc/client": "^1.13.7"
  "@orpc/openapi": "^1.13.7"
  "@orpc/server": "^1.13.7"
  "@orpc/tanstack-query": "^1.13.7"
  "@orpc/zod": "^1.13.7"
  "@tanstack/react-form": "^1.28.5"
  "@tanstack/react-query": "^5.90.21"
  "@types/node": "^22.19.15"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.2.3"
  ai: "^6.0.127"
  alchemy: "^0.89.0"
  better-auth: 1.5.5
  crossws: "^0.4.1"
  dotenv: "^17.3.1"
  hono: "^4.12.7"
  libsql: 0.5.22
  lucide-react: "^0.577.0"
  next-themes: "^0.4.6"
  react: "^19.2.4"
  react-dom: "^19.2.4"
  sonner: "^2.0.7"
  tailwindcss: "^4.2.1"
  typescript: "~5.9.3"
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.11
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  wrangler: "^4.73.0"
  zod: "^4.3.6"
overrides:
  "@libsql/client": "catalog:"
  "@tanstack/react-query": "catalog:"
  "@types/node": "catalog:"
  crossws: "catalog:"
  typescript: "catalog:"
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
